# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:yEgX86cy1FgJhmjGn0KPhORJqEMFrPZ9ezXrXkfnhVomeiEZf3HzgmXafqvjGf9g99r6bzguWcTTlFqsKtcgA3bfJtAa8hT/HJEvQd9IlTx7Sgl2eqmwbU+ANbrtTzUKIrTrbimoIr+9sBDKz21ybJ2uiOc/V72lODonCO+evCzWGXZjFdU0Glhv+kcZC0GLH5VTu3mQD6d8Z+a1E8z+oMk8yZpOAjNrR7uuzWn92Q==,iv:xEArUNnAyx0M8CpNgWMRCTDHCT8ZzTrnopkTdtZHBhE=,tag:0xwqHsCokej7Eg+ziRjmog==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age144z64fx2g9juktp4aydnecc2nrh7mp85yg55sqxsa27jg23w734s3y28v3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN083cFRFRXFmeXB2SVdK
        dnM1TnZ4ZG5uUVcrbFVGejUyOTIxcEpUcXhjClM5WkJLN21JSHN4SUdTWDA4L1B1
        TW9TYkNOOUpRZWhqQXNqQjZuWG1JUTQKLS0tIHU5VGNYY3FMMzErR2xWeS9XTEZJ
        SWlVMzRRanpJQU9xNG84b29Ib1liaHcKmFAfXQV2UHpMaW/1Y/BBpvJc/sGbXUAz
        +ezV9dDjDI2RCf/bzWll4fLLLIYOOvAioy2DtBFGO7Tb9vxxWDCvFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T15:26:43Z"
  mac: ENC[AES256_GCM,data:woNs5z3s5tkf/5SzqQUmAeZhIxrxWStuWNhk/TSwgJmZNwZyI4uyKvL1hSjuHkJJaZlfoBI1u6BwG6uDu2q5/ptI2015HEvNrajqUKrrrHW8hZtsgLBIbSdwjHJvtokNUg+bFnsHsR0AZl76w++DY4JFjraY0mlQ2qseocO12t0=,iv:sP4QgJZhwXb/j1UC8BEejJqwlZKV5icprho5ehhMW9I=,tag:HKv/Fo4qxyn9yxnZFVPbsg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
