# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:IC2qkn4RK2QxWRSF/tt+9+ZisXdWY/kA+RM3tr6RqK0=,iv:n55ecYTlOw4IwuArYhQTWBzvqeClfCE40DDQLy2lEtk=,tag:Y2aDQfFW6ToBxIbTJq7ydg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age144z64fx2g9juktp4aydnecc2nrh7mp85yg55sqxsa27jg23w734s3y28v3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeVQwb0VXUklvaDZObnJa
        N0lZSkhublRCN3hpYWVqOE9LcDV1MUJWNlVvCk1vY0VacTQ3bWVZaWFQN0xMYTJ6
        Vm43RkpwWEZrbFYwZjdBMnN5di9sY28KLS0tIFNvMWw0dk9lclZsa3hVdFdHUWJ2
        U2J5aTJha1JvcVVvUEx1aEgydFBuZmsKr2rm+8E66NybxUmBFzRaa6ehCXOC07B7
        35Pt4PMODxAfLJOmcRfB+BWEHJd5pySrWKQoUOBNLj5nKkPJdH6DxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T16:31:21Z"
  mac: ENC[AES256_GCM,data:0YVrqcY6Kv1iuGp9uS7gv95nOn9n89Ail14f90WeDqxm2PWWUjBDabFOnvy7ppTFVfV3ZXDlxHu+gOQ1DMSGDX+kxzYJ3nPhHT5MevA9eD85M36shLUVRayNpMb5q3b5m8H1opz0qoaegGkoWV7pAUp11+xBosBctSLQV0Jz+tU=,iv:qg2Eb6GqisQkF/OFjdgVHlxBm1DXoWEpNcSRRNJni94=,tag:r71/tj//qmnRCvwM3Ywcgw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
